 'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{DatabaseSync}=require('node:sqlite'),validate=require('./skin-worker.cjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const fail=(status,message)=>Object.assign(Error(message),{status});
function createSkins({directory,storage,authenticateAdmin,publicUploads=true,trustProxy=false}){
 fs.mkdirSync(directory,{recursive:true});const db=new DatabaseSync(path.join(directory,'skins.sqlite'));
 db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS publishers(id TEXT PRIMARY KEY,secret TEXT UNIQUE NOT NULL,created INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS skins(id TEXT PRIMARY KEY,owner TEXT NOT NULL,revision INTEGER NOT NULL,visibility TEXT NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL,downloads INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS skin_revisions(id TEXT NOT NULL,revision INTEGER NOT NULL,data TEXT NOT NULL,PRIMARY KEY(id,revision));
 CREATE TABLE IF NOT EXISTS skin_uploads(owner TEXT NOT NULL,upload TEXT NOT NULL,fingerprint TEXT NOT NULL,skin TEXT NOT NULL,revision INTEGER NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(owner,upload));`);
 let tail=Promise.resolve(),pending=0,downloadsActive=0,closed=false;const rates=new Map();
 function rate(key,max,window=60000){const now=Date.now();let r=rates.get(key);if(!r||r.until<now)r={count:0,until:now+window};if(++r.count>max)throw fail(429,'Too many requests. Please try again later.');rates.set(key,r);if(rates.size>20000){for(const [k,v]of rates)if(v.until<now)rates.delete(k);if(rates.size>20000)rates.delete(rates.keys().next().value);}}
 function account(token){if(typeof token!=='string'||!/^sk_[a-f0-9]{64}$/.test(token))throw fail(401,'Publish from your own skin account.');const row=db.prepare('SELECT id FROM publishers WHERE secret=?').get(hash(token));if(!row)throw fail(401,'Your skin publishing identity is unavailable.');return row.id;}
 function register(){if(!publicUploads)throw fail(403,'Skin uploads are currently closed.');const id=crypto.randomBytes(16).toString('hex'),token='sk_'+crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO publishers VALUES(?,?,?)').run(id,hash(token),Date.now());return {id,token};}
 function get(id,rev){if(!/^[a-f0-9]{16}$/.test(id||''))throw fail(404,'Skin not found.');const skin=db.prepare("SELECT * FROM skins WHERE id=? AND visibility<>'removed'").get(id);if(!skin)throw fail(404,'Skin not found.');const row=db.prepare('SELECT data FROM skin_revisions WHERE id=? AND revision=?').get(id,rev||skin.revision);if(!row)throw fail(404,'Skin revision not found.');return {...JSON.parse(row.data),downloads:skin.downloads,visibility:skin.visibility};}
 function list(params={},owner){const page=Math.max(1,Math.min(10000,Number(params.page)||1)),base=Number(params.base),query=String(params.search||'').slice(0,100);let where=owner?'s.owner=? AND s.visibility<>\'removed\'':"s.visibility='public'",args=owner?[owner]:[];
 if(Number.isInteger(base)&&base>=1&&base<=11){where+=" AND json_extract(r.data,'$.base')=?";args.push(base);}
 if(query){where+=" AND (json_extract(r.data,'$.name') LIKE ? ESCAPE '\\' OR json_extract(r.data,'$.author') LIKE ? ESCAPE '\\')";const q='%'+query.replace(/[\\%_]/g,'\\$&')+'%';args.push(q,q);}
 const order=params.sort==='popular'?'s.downloads DESC,s.updated DESC,s.id':'s.updated DESC,s.id';
 const rows=db.prepare(`SELECT s.*,r.data FROM skins s JOIN skin_revisions r ON r.id=s.id AND r.revision=s.revision WHERE ${where} ORDER BY ${order} LIMIT 25 OFFSET ?`).all(...args,(page-1)*24);
 return {page,more:rows.length>24,items:rows.slice(0,24).map(r=>({...JSON.parse(r.data),downloads:r.downloads,visibility:r.visibility}))};}
 function publish(input,owner){if(closed)throw fail(503,'Skin service is stopping.');if(pending>=3)throw fail(503,'Uploads are busy. Please try again shortly.');pending++;
 const task=tail.then(async()=>{
 if(!publicUploads)throw fail(403,'Skin uploads are currently closed.');if(!/^[a-zA-Z0-9-]{8,80}$/.test(input?.uploadId||''))throw fail(400,'Invalid upload request.');
 const fingerprint=hash(JSON.stringify(input)),existing=db.prepare('SELECT * FROM skin_uploads WHERE owner=? AND upload=?').get(owner,input.uploadId);
 if(existing){if(existing.fingerprint!==fingerprint)throw fail(409,'This upload request changed. Start a new upload.');return get(existing.skin,existing.revision);}
 const id=input.id||crypto.randomBytes(8).toString('hex');if(!/^[a-f0-9]{16}$/.test(id))throw fail(400,'Invalid skin ID.');const prior=db.prepare('SELECT * FROM skins WHERE id=?').get(id);
 if(input.id&&(!prior||prior.owner!==owner||prior.visibility==='removed'))throw fail(403,'Only the original publisher can update this skin.');
 if(prior&&Number(input.baseRevision)!==prior.revision)throw fail(409,'This skin has changed. Refresh before updating.');
 const daily=db.prepare('SELECT count(*) n FROM skin_uploads WHERE owner=? AND created>?').get(owner,Date.now()-86400000).n;if(daily>=20)throw fail(429,'You can publish up to 20 skin revisions per day.');
 if(!prior&&db.prepare("SELECT count(*) n FROM skins WHERE owner=? AND visibility<>'removed'").get(owner).n>=100)throw fail(429,'Your library has reached 100 uploads.');
 let art;try{art=await validate(input);}catch(e){throw fail(400,e.message);}if(prior&&get(id).base!==art.base)throw fail(400,'An update must keep the same character template.');
 const pack=JSON.parse(art.bytes);pack.id='community-'+id;art.bytes=Buffer.from(JSON.stringify(pack));if(art.bytes.length>16*1024*1024)throw fail(400,'The skin package exceeds 16 MB.');art.hash=hash(art.bytes);
 try{await storage.put('blobs/'+art.hash+'.json',art.bytes);await storage.put('blobs/'+art.iconHash+'.png',art.icon);}catch{throw fail(502,'Storage upload failed. The skin was not published. Retry this upload.');}
 const revision=(prior?.revision||0)+1,now=Date.now(),data={id,revision,name:art.name,author:art.author,description:art.description,base:art.base,templateFingerprint:art.templateFingerprint,hash:art.hash,size:art.bytes.length,iconHash:art.iconHash,iconSize:art.icon.length,artRevision:art.artRevision,created:prior?.created||now,updated:now,package:'/api/skins/'+id+'/'+revision+'/download',preview:'/api/skins/'+id+'/'+revision+'/icon'};
 db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO skin_revisions VALUES(?,?,?)').run(id,revision,JSON.stringify(data));db.prepare('INSERT INTO skins(id,owner,revision,visibility,created,updated) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET revision=excluded.revision,visibility=excluded.visibility,updated=excluded.updated').run(id,owner,revision,art.visibility,data.created,now);db.prepare('INSERT INTO skin_uploads VALUES(?,?,?,?,?,?)').run(owner,input.uploadId,fingerprint,id,revision,now);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return get(id,revision);
 });tail=task.catch(()=>{});return task.finally(()=>pending--);}
 const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data));};
 async function body(req){let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>20*1024*1024)throw fail(413,'Skin uploads must be under 20 MB.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString());}catch{throw fail(400,'Invalid upload JSON.');}}
 async function handle(req,res){const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/api/skins')&&url.pathname!=='/skins'&&!url.pathname.startsWith('/skins/'))return false;
 try{let ip=req.socket.remoteAddress||'local';if(trustProxy){const candidate=String(req.headers['x-forwarded-for']||'').split(',').at(-1)?.trim();if(require('node:net').isIP(candidate))ip=candidate;}rate('read:'+ip,300);
 const token=String(req.headers.authorization||'').replace(/^Bearer /,'');
 if(url.pathname==='/api/skins/health'){if(req.method!=='GET')throw fail(405,'Use GET.');json(res,200,{ok:true,service:'jimbob-skins',version:1,uploads:publicUploads});}
 else if(url.pathname==='/api/skins/accounts'){if(req.method!=='POST')throw fail(405,'Use POST.');rate('account:'+ip,4,86400000);json(res,201,register());}
 else if(url.pathname==='/api/skins'||url.pathname==='/api/skins/mine'){
 if(req.method==='GET')json(res,200,list(Object.fromEntries(url.searchParams),url.pathname.endsWith('/mine')?account(token):undefined));
 else if(req.method==='POST'&&url.pathname==='/api/skins'){const owner=account(token);rate('upload:'+ip,20);json(res,201,await publish(await body(req),owner));}else throw fail(405,'Use GET or POST.');}
 else if(url.pathname.startsWith('/api/skins/')){const match=/^\/api\/skins\/([a-f0-9]{16})(?:\/(\d{1,6})\/(download|icon))?$/.exec(url.pathname);if(!match)throw fail(404,'Skin not found.');const [,id,rev,kind]=match;
 if(req.method==='DELETE'&&!kind){let admin=false;try{authenticateAdmin?.(token);admin=!!authenticateAdmin;}catch{}const row=db.prepare('SELECT owner FROM skins WHERE id=?').get(id);if(!row||(!admin&&row.owner!==account(token)))throw fail(403,'Only the publisher can remove this skin.');db.prepare("UPDATE skins SET visibility='removed' WHERE id=?").run(id);json(res,200,{removed:true});}
 else{if(!['GET','HEAD'].includes(req.method))throw fail(405,'Use GET.');const row=get(id,rev?Number(rev):undefined);if(!kind)json(res,200,row);else{const digest=kind==='icon'?row.iconHash:row.hash,size=kind==='icon'?row.iconSize:row.size,etag='"'+digest+'"';if(req.headers['if-none-match']===etag){res.writeHead(304);res.end();}else{if(downloadsActive>=8)throw fail(503,'Skin downloads are busy. Try again shortly.');downloadsActive++;let bytes;try{bytes=await storage.get('blobs/'+digest+(kind==='icon'?'.png':'.json'));}finally{downloadsActive--;}if(bytes.length!==size||hash(bytes)!==digest)throw fail(502,'Stored skin verification failed.');res.writeHead(200,{'content-type':kind==='icon'?'image/png':'application/json','content-length':bytes.length,'cache-control':'public,max-age=86400',etag,'x-content-type-options':'nosniff',...(kind==='download'?{'content-disposition':'attachment; filename="'+id+'.jskin"'}:{})});res.end(req.method==='HEAD'?undefined:bytes);if(kind==='download'&&req.method==='GET')db.prepare('UPDATE skins SET downloads=downloads+1 WHERE id=?').run(id);}}}}
 else{if(req.method!=='GET')throw fail(405,'Use GET.');const file=url.pathname==='/skins'?'skins.html':url.pathname==='/skins/app.js'?'skins-app.js':url.pathname==='/skins/style.css'?'skins-style.css':null;if(!file)throw fail(404,'Page not found.');res.writeHead(200,{'content-type':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript; charset=utf-8':'text/css; charset=utf-8','content-security-policy':"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; frame-ancestors 'none'",'x-content-type-options':'nosniff'});res.end(fs.readFileSync(path.join(__dirname,'public',file)));}
 }catch(e){if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'The skin service is unavailable. Try again shortly.'});else res.end();}return true;}
 return {handle,register,account,publish,list,get,close:async()=>{closed=true;await tail;db.close();}};
}
module.exports={createSkins};
